name: app_emergency
description: "Sistema de Emergencias"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  provider: ^6.0.5
  nested: ^1.0.0
  shared_preferences: ^2.2.0
  image_picker: ^1.0.4
  google_fonts: ^6.1.0
  url_launcher: ^6.2.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Configuración de flutter_launcher_icons (fuera de la sección flutter)
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/logo.png"
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  
  # Descomentar y agregar los assets
  assets:
    - assets/logo.png